change card to articles in html

diff --git a/scripts/gitpush b/scripts/gitpush
--- a/scripts/gitpush
+++ b/scripts/gitpush
@@ -7,18 +7,22 @@ if [ $# -eq 0 ]; then
   exit 1
 fi
 
+npm run build:all
+# Check the exit code of the previous command (npm run build:all)
+if [ $? -ne 0 ]; then
+  echo "❌ npm build failed. Exiting script."
+  exit 1
+fi
 
 # Git add all files
-echo "🚀 Staging all changes..."
+echo "Staging all changes..."
 git add .
 
 # Git commit with all arguments as the message. The quotes around "$@" are important!
 echo "📦 Committing with message: '$@'"
 git commit -m "$@"
 
-# Git push to the main branch
-echo "⬆️ Pushing to the main branch..."
-git push origin main
+
 
 echo "✅ Success! All changes have been pushed to main."
 
